package vigenere

var atoi = map[byte]int{
	byte('A'): 0,
	byte('B'): 1,
	byte('C'): 2,
	byte('D'): 3,
	byte('E'): 4,
	byte('F'): 5,
	byte('G'): 6,
	byte('H'): 7,
	byte('I'): 8,
	byte('J'): 9,
	byte('K'): 10,
	byte('L'): 11,
	byte('M'): 12,
	byte('N'): 13,
	byte('O'): 14,
	byte('P'): 15,
	byte('Q'): 16,
	byte('R'): 17,
	byte('S'): 18,
	byte('T'): 19,
	byte('U'): 20,
	byte('V'): 21,
	byte('W'): 22,
	byte('X'): 23,
	byte('Y'): 24,
	byte('Z'): 25,
}

var itoa = map[int]byte{
	0:  byte('A'),
	1:  byte('B'),
	2:  byte('C'),
	3:  byte('D'),
	4:  byte('E'),
	5:  byte('F'),
	6:  byte('G'),
	7:  byte('H'),
	8:  byte('I'),
	9:  byte('J'),
	10: byte('K'),
	11: byte('L'),
	12: byte('M'),
	13: byte('N'),
	14: byte('O'),
	15: byte('P'),
	16: byte('Q'),
	17: byte('R'),
	18: byte('S'),
	19: byte('T'),
	20: byte('U'),
	21: byte('V'),
	22: byte('W'),
	23: byte('X'),
	24: byte('Y'),
	25: byte('Z'),
}
